module.exports = {
    PRE_JOIN: 'pre_join',
    JOIN_TABLE: 'join_table',
    LEFT_ROOM: 'left_room',
    DISCONNECT: 'disconnect',
    CLICK_CELL: 'click_cell',
    SUBMIT_JOIN: 'submit_join',
    COUNT_PLAYER: 'count_player',
    OPPONENT: 'opponent',
    WINNER: 'winner',
    MESS_WIN: 'You Win :)!',
    MESS_LOST: 'You Lost :(',
    LOST: '',
    YOUDISCONNECT: 'youdisconnect',
    MESS_DISCONNECT: 'you disconnected',
    SERVER_SEND_DATA: 'server_send_data',
    YOUT_TURN: 'your_turn',
    WAIT_PLAYER: 'wait_player',
    MESS_WAIT: 'Please wait other player'
}